mv ./xhtmlxtras/cite.htm ./xhtmlxtras/cite.htm.pt
mv ./xhtmlxtras/del.htm ./xhtmlxtras/del.htm.pt
mv ./xhtmlxtras/acronym.htm ./xhtmlxtras/acronym.htm.pt
mv ./xhtmlxtras/attributes.htm ./xhtmlxtras/attributes.htm.pt
mv ./xhtmlxtras/ins.htm ./xhtmlxtras/ins.htm.pt
mv ./xhtmlxtras/abbr.htm ./xhtmlxtras/abbr.htm.pt
mv ./template/blank.htm ./template/blank.htm.pt
mv ./template/template.htm ./template/template.htm.pt
mv ./advhr/rule.htm ./advhr/rule.htm.pt
mv ./media/media.htm ./media/media.htm.pt
mv ./silvaimage/image.htm ./silvaimage/image.htm.pt
mv ./silvalink/link.htm ./silvalink/link.htm.pt
mv ./fullpage/fullpage.htm ./fullpage/fullpage.htm.pt
mv ./table/table.htm ./table/table.htm.pt
mv ./table/row.htm ./table/row.htm.pt
mv ./table/merge_cells.htm ./table/merge_cells.htm.pt
mv ./table/cell.htm ./table/cell.htm.pt
mv ./fullscreen/fullscreen.htm ./fullscreen/fullscreen.htm.pt
mv ./inlinepopups/template.htm ./inlinepopups/template.htm.pt
mv ./searchreplace/searchreplace.htm ./searchreplace/searchreplace.htm.pt
mv ./style/props.htm ./style/props.htm.pt
mv ./emotions/emotions.htm ./emotions/emotions.htm.pt
mv ./paste/pasteword.htm ./paste/pasteword.htm.pt
mv ./paste/pastetext.htm ./paste/pastetext.htm.pt
mv ./advlink/link.htm ./advlink/link.htm.pt
mv ./advimage/image.htm ./advimage/image.htm.pt
mv ./example/dialog.htm ./example/dialog.htm.pt
mv ./silvaxhtmlxtras/cite.htm ./silvaxhtmlxtras/cite.htm.pt
mv ./silvaxhtmlxtras/del.htm ./silvaxhtmlxtras/del.htm.pt
mv ./silvaxhtmlxtras/acronym.htm ./silvaxhtmlxtras/acronym.htm.pt
mv ./silvaxhtmlxtras/attributes.htm ./silvaxhtmlxtras/attributes.htm.pt
mv ./silvaxhtmlxtras/ins.htm ./silvaxhtmlxtras/ins.htm.pt
mv ./silvaxhtmlxtras/abbr.htm ./silvaxhtmlxtras/abbr.htm.pt
