tinyMCE.addI18n('en.silvaimage_dlg',{
tab_silva:"Silva Image",
tab_advanced:"Advanced",
tab_ext:"External Image",
silva:"Silva",
ext:"External Image",
title:"Title",
alt:"Image description",
preview:"Preview",
constrain_proportions:"Constrain proportions",
langdir:"Language direction",
langcode:"Language code",
long_desc:"Long description link",
style:"Style",
classes:"Classes",
ltr:"Left to right",
rtl:"Right to left",
id:"Id",
map:"Image map",
swap_image:"Swap image",
alt_image:"Alternative image",
mouseover:"for mouse over",
mouseout:"for mouse out",
misc:"Miscellaneous",
example_img:"Appearance preview image",
missing_alt:"Are you sure you want to continue without including an Image Description? Without it the image may not be accessible to some users with disabilities, or to those using a text browser, or browsing the Web with images turned off.",
dialog_title:"Insert/edit image",
extsrc:"Image URL",
list:"Image list",
border:"Border",
dimensions:"Dimensions",
vspace:"Vertical space",
hspace:"Horizontal space",
align:"Alignment",
align_baseline:"Baseline",
align_top:"Top",
align_middle:"Middle",
align_bottom:"Bottom",
align_texttop:"Text top",
align_textbottom:"Text bottom",
align_left:"Left",
align_right:"Right",
image_list:"Image list",
silvasrc:"Silva Image",
silvaget_reference:"Lookup Silva Image",
silvasize:"Image Size",
silvasize_web:"Standard (Web Format)",
silvasize_hires:"Hi Resolution",
silvasize_thumbnail:"Thumbnail"
});